= Value Objects in Java Talk
:toc: macro

Demo code about value objects and how to create them in Java.

toc::[]

== Purpose

This source demonstrates how to create value objects in Java using various annotation processors.

== Evaluated Libraries

- https://github.com/google/auto/blob/master/value/userguide/index.md[AutoValue]
- https://freebuilder.inferred.org[FreeBuilder]
- https://immutables.github.io[Immutables]
- https://projectlombok.org[Project Lombok]

Also, simple https://www.scala-lang.org[Scala] and https://kotlinlang.org[Kotlin] examples are
included for demonstration purposes.

== Structure

In `+de.melsicon.talk.value.simple.*+` We have simple classes, one `+EmailAddress+` which demonstrates
the power of being able to check value objects for consistency durin construction and `+Person+`,
which show how different libraries handle optional parameters and documentation propagation.

`+de.melsicon.talk.value.inheritance.*+` and `+de.melsicon.talk.value.composition.*+` demonstrates
the https://en.wikipedia.org/wiki/Composition_over_inheritance[composition over inheritance]
principle and why value objects can not meaningfully extend each other.

== Running

=== Prerequisites

You need https://github.com/bazelbuild/bazelisk[Bazelisk] installed, with https://brew.sh[HomeBrew]
just use [source,shell]`brew install bazelbuild/tap/bazelisk`.
See also https://docs.bazel.build/versions/4.0.0/install-bazelisk.html[Installing Bazel using
Bazelisk].

Also, Java needs to be https://adoptopenjdk.net/installation.html[installed].

=== Main App

The main app simply demonstrates the `toString` method with a simple structure. Run it with
[source,shell]
----
bazel run //:value-comparison
----

=== Tests

To run all tests, use

[source,shell]
----
bazel test //...
----
