#load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary")

#kt_jvm_library(
#    name = "kotlin",
#    srcs = glob(["*.kt"]),
#    visibility = ["//visibility:public"],
#    deps = [
#        "@maven//:commons_validator_commons_validator",
#    ],
#)
